### ISSUE TITLE
Can't build using 'gradle build'

### ISSUE THREAD

**Issue by illia-romanenko** [heroiclabs/nakama-java#20]
Hi
I'm trying to build 'nakama-java' using 'gradle build' but it fails.

> Could not get unknown property 'GradleVersion' for object of type org.ajoberstar.gradle.git.publish.GitPublishExtension.

When I remove "GradleVersion.current().version":

     commitMessage = "Published javadoc" + project.version + "via Gradle " + GradleVersion.current().version + "."

it then fails with:
Build file '/Users/illia/Documents/Nakama/nakama-java/build.gradle' line: 206

> Could not find method sourcesJar() for arguments [build_8t0ai7vfm0udn1fmw1bins870$_run_closure10$_closure46$_closure47$_closure48@5294b0bf] on object of type org.gradle.api.publish.maven.internal.publication.DefaultMavenPublication.

If I remove publishing section completely I run into this issue:

> Task :compileJava FAILED
/Users/illia/Documents/Nakama/nakama-java/src/main/java/com/heroiclabs/nakama/SocketClient.java:20: error: package com.heroiclabs.nakama.api does not exist
import com.heroiclabs.nakama.api.Rpc;
                                ^
/Users/illia/Documents/Nakama/nakama-java/src/main/java/com/heroiclabs/nakama/Client.java:369: error: cannot find symbol
    ListenableFuture<Group> createGroup(@NonNull final Session session, @NonNull final String name);
                     ^
  symbol:   class Group
  location: interface Client
/Users/illia/Documents/Nakama/nakama-java/src/main/java/com/heroiclabs/nakama/Client.java:378: error: cannot find symbol
    ListenableFuture<Group> createGroup(@NonNull final Session session, @NonNull final String name, final String description);
                     ^

Do you have any up-to-date instructions on how to build nakama-java?

**Comment by novabyte** [comment]
Hey @illia-romanenko what version of gradle do you use?

**Comment by illia-romanenko** [comment]
@novabyte  thanks for such a quick response Chris!

Gradle 5.2.1
------------------------------------------------------------

Build time:   2019-02-08 19:00:10 UTC
Revision:     f02764e074c32ee8851a4e1877dd1fea8ffb7183

Kotlin DSL:   1.1.3
Kotlin:       1.3.20
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          9.0.4 (Oracle Corporation 9.0.4+11)
OS:           Mac OS X 10.13.6 x86_64

**Comment by novabyte** [comment]
@illia-romanenko I've just updated to the Gradle 5.2.1 release and you're right. The guys at Gradle have broken their plugin API again so we'll have to update the build process to be compatible again. This will likely require us to drop the Gradle 4+ releases. The quickest solution is to drop down to Gradle 4 release for now.

**Comment by illia-romanenko** [comment]
@novabyte that's very unfortunate but it is what it is, thanks for checking this for me - I'll give it a try.

**Comment by ipolev** [comment]
It's not build on gradle 4.10.1

**Comment by mofirouz** [comment]
@ipolev what's the error you get when using Gradle 4.10?

**Comment by ipolev** [comment]
@mofirouz 
package com.heroiclabs.nakama.api does not exist

**Comment by mofirouz** [comment]
Created https://github.com/heroiclabs/nakama-java/issues/28 to track updating client library to Gradle 5.
