### ISSUE TITLE
Update to Gradle 5.

### ISSUE THREAD

**Issue by mofirouz** [heroiclabs/nakama-java#28]
Currently the client library can only be built using Gradle 4 (latest tested version is 4.10.3). We should move this to use Gradle 5 and publish the library into central repositories.

**Comment by mthakuri** [comment]
@mofirouz Will this compile with OpenJDK 1.8 and above or need Oracle Java 1.7+ only? Coz I'm getting error while running >gradle build

**ERROR**
warning: [options] bootstrap class path not set in conjunction with -source 1.7
D:\Workspace\Others\nakama-java-2.0.4\src\main\java\com\heroiclabs\nakama\AbstractSocketListener.java:19: error: package com.heroiclabs.nakama.api does not exist
import com.heroiclabs.nakama.api.ChannelMessage;
.
.
.
.
.
.
Multiple of these

**Comment by mthakuri** [comment]
@mofirouz I know it's must be a busy schedule for you. But can you please guide me with this or provide something I can look into.
